baseURL = 'https://www.danielwells.me/'
languageCode = 'en-us'
title = 'Daniel Wells'
theme = 'hyde'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Menus]
  main = [
	{Name = "Blog", URL = "/posts/", Pre = 'fas fa-feather-alt', weight = -11},
#	{Name = "Twitter", URL = "https://twitter.com/danieljohnwells", Pre = "fab fa-twitter", weight = -10},
#	{Name = "Email", URL = "mailto:email@danielwells.me", Pre = 'fas fa-envelope', weight = -9},
#	{Name = "Github", URL = "https://github.com/daniel-wells", Pre = 'fab fa-github', weight = -8},
#	{Name = "LinkedIn", URL = "https://uk.linkedin.com/in/danieljohnwells", Pre = 'fab fa-linkedin', weight = -7},
#	{Name = "Links", URL = "/links/", Pre = 'fas fa-ellipsis-h', weight = -6}
  ]

[params]
  description = "Molecular biologist turned statistician."

[params.social]
	twitter = "DanielJohnWells"
	keybase = "danielwells"
	github = "daniel-wells"
	linkedin = "danieljohnwells"
	email = "email@danielwells.me"
	googlescholar = "ysh9R0MAAAAJ"
	orcid = "0000-0002-2007-8978"
	wikipedia = "D_Wells"
	spotify = "1111629369"
	lastfm = "dannywells"
 # 	facebook = "Daniel.John.Wells"
